# Generated by Django 3.0.5 on 2020-05-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200506_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
